### ISSUE TITLE
Add a new shop demo

### ISSUE THREAD

**Issue by danielfarrelly** [mlabs-haskell/godot-cardano#48]
Our first demo has been useful (and still is) for testing new functionality, but now we need a more polished and featured demo for milestone 5.

# Shop demo

## Introduction

The shop demo consists of a simple UI showcasing a selection of NFTs available from a smart contract. The NFTs themselves will be CIP68 tokens, with certain attributes dictating how they look in the UI (e.g: their colour). The demo will contain a separate UI node for the wallet itself, which we hope can be re-used as a starting point for any developer interested in the framework.

The writing of the demo will be done partly in group sessions. The goal of this is to bring as many eyes as possible so we can identify problems in our API. Some issues identified so far in the sessions: #50, #51, #52 .

## Goals

1. Providing an example and starting point for any interested developer, as explained in Milestone 5.
2. Identify current issues in our API, so that we can fix them and improve the framework.

## Tasks

- [x] NFT Shop UI
- [ ] Wallet UI
- [x] CIP68 token minting (related issue: #57 )
    * [x] Improved on #57 by adding fungible token support
- [x] Tracking transaction progress in UI (In progress)
- [ ] Add scene for pre-minting the tokens and locking them in a sale validator (In progress)
- [x] Support reference inputs
- ...
